replicaCount: 1

image:
  repository: docker.io/springcommunity/spring-petclinic
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  name: ""
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80   # (optional, depends on your template)


ingress:
  enabled: true
  className: nginx
  hosts:
    - host: petclinic.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
