replicaCount: 1

image:
  repository: docker.io/springcommunity/spring-petclinic
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: petclinic.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
